version: '3'
services:
  node:
    container_name: node
    restart: always
    build: .
    ports:
      - 8080:3000
    volumes:
      - ./:/code
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - node

volumes:
 mongodb:
