- hosts:
    - all
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
      become: yes
      become_user: root
      become_method: sudo
       
    # use files parameter to use multiple docker-compose.yml files
    # - name: deploy Docker Compose stack
    #   docker_compose:
    #     project_src: /opt/node-mongodb-pipeline
    #     files:
    #     - docker-compose.yml

    - file:
        path: /opt/node-mongodb-pipeline/
        state: directory
        owner: ec2-user
        mode: 0755
      become: yes
      become_user: root
      become_method: sudo

    - name: Git pull project
      git:
        repo: 'https://github.com/catalincostea/node-mongodb-pipeline.git'
        dest: /opt/node-mongodb-pipeline

    - name: Run container
      become: True
      shell:
        cmd: "docker-compose up -d --build"
        chdir: /opt/node-mongodb-pipeline/
