- hosts:
    - all
  tasks:
    - name: Just get information about the repository whether or not it has already been cloned locally
      git:
        repo: 'https://github.com/catalincostea/node-mongodb-pipeline.git'
        dest: /opt/node-mongodb-pipeline

    # use files parameter to use multiple docker-compose.yml files
    # - name: deploy Docker Compose stack
    #   docker_compose:
    #     project_src: /opt/node-mongodb-pipeline
    #     files:
    #     - docker-compose.yml

    - name: Run container
      become: True
      shell:
        cmd: "docker-compose up -d --build"
        chdir: /opt/node-mongodb-pipeline/
