- hosts:
    - all
  tasks:
    - name: Just get information about the repository whether or not it has already been cloned locally
      ansible.builtin.git:
        repo: 'https://github.com/catalincostea/node-mongodb-pipeline.git'
        dest: /opt/node-mongodb-pipeline
