- hosts:
    - all
  tasks:
    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes

    - name: Git pull project
      git:
        repo: 'https://github.com/catalincostea/node-mongodb-pipeline.git'
        dest: /opt/node-mongodb-pipeline

    # use files parameter to use multiple docker-compose.yml files
    # - name: deploy Docker Compose stack
    #   docker_compose:
    #     project_src: /opt/node-mongodb-pipeline
    #     files:
    #     - docker-compose.yml

    - file:
        path: /opt/node-mongodb-pipeline/
        state: directory
        mode: 0755
        # owner: foo
        # group: foo

    - name: Run container
      become: True
      shell:
        cmd: "docker-compose up -d --build"
        chdir: /opt/node-mongodb-pipeline/
