- hosts:
    - all
  tasks:
    - name: Login, tag and publish image
      command: "{{item}}"
      with_items:
       - set
       - docker tag node-mongodb-pipeline_node:latest catalincostea/node-mongoose:latest
       - docker login -u catalincostea -p {{wr_token}}
       - docker push catalincostea/node-mongoose:latest
      env:
        wr_token="{{wr_token}}"


# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname

# docker tag node-mongodb-pipeline_node:latest catalincostea/node-mongoose:latest
# docker push catalincostea/node-mongoose:latest



